### ISSUE TITLE
Kustomize meta issue

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#973]
- [ ] Support setting replicas as a first class field (like images)
- [ ] Support fine grain control of configuring configmap generation behave - e.g. generate hash suffix
- [ ] Clarify that order of resources means nothing
- [ ] Deleting should be done in the reverse order
- [ ] Change labels of duplicates Pods for DaemonSets
- [ ] Namespace Resources vs Namespace field
- [ ] Story on cleaning up generated resources

**Comment by vasu1124** [comment]
I was wondering how kustomize could help with runtime input derived from other resource.
A typical example is described in https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/#setup-dns , where I need to set a field or data item with a spec of a runtime resource. I see a lot of cases where shell scripting is imperatively (mis)used with
```
kubectl apply -f - <<EOF
apiVersion: v1
...
        cache 30
        proxy . $(kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP})
    }
EOF
```

Is such scenario actually in scope for kustomize? If yes, are there any links on how you are thinking on solving it? 

Thanks!

**Comment by jbrette** [comment]
@pwittrock #1451 is addressing:

Clarify that order of resources means nothing
Deleting should be done in reverse order

by allowing the user to run the following command:
```bash
kustomize build <xxx> --reorder=kubectlapply | kubectl apply -f -
```
and
```bash
kustomize build <xxx> --reorder=kubectldelete | kubectl delete -f -
```
